<?php
/**
 * SuiteCRM F&I Deal Center - List View Definitions
 * 
 * This file defines the fields and layout for the F&I Deal Center list view,
 * optimized to display key financial information at a glance.
 */

$listViewDefs['DM_FIDeals'] = array(
    'DEAL_NUMBER' => array(
        'width' => '10%',
        'label' => 'LBL_DEAL_NUMBER',
        'link' => true,
        'default' => true,
    ),
    'NAME' => array(
        'width' => '15%',
        'label' => 'LBL_NAME',
        'link' => true,
        'default' => true,
    ),
    'CUSTOMER_NAME' => array(
        'width' => '15%',
        'label' => 'LBL_CUSTOMER_NAME',
        'id' => 'CUSTOMER_ID',
        'link' => true,
        'module' => 'Accounts',
        'default' => true,
        'ACLTag' => 'ACCOUNTS',
        'related_fields' => array('customer_id'),
    ),
    'VEHICLE_NAME' => array(
        'width' => '15%',
        'label' => 'LBL_VEHICLE_NAME',
        'id' => 'VEHICLE_ID',
        'link' => true,
        'module' => 'DM_VehiclesInventory',
        'default' => true,
        'related_fields' => array('vehicle_id'),
    ),
    'DEAL_STATUS' => array(
        'width' => '8%',
        'label' => 'LBL_DEAL_STATUS',
        'default' => true,
    ),
    'FINANCE_METHOD' => array(
        'width' => '8%',
        'label' => 'LBL_FINANCE_METHOD',
        'default' => true,
    ),
    'SALES_PRICE' => array(
        'width' => '10%',
        'label' => 'LBL_SALES_PRICE',
        'align' => 'right',
        'default' => true,
        'currency_format' => true,
    ),
    'MONTHLY_PAYMENT' => array(
        'width' => '10%',
        'label' => 'LBL_MONTHLY_PAYMENT',
        'align' => 'right',
        'default' => true,
        'currency_format' => true,
    ),
    'TOTAL_GROSS' => array(
        'width' => '10%',
        'label' => 'LBL_TOTAL_GROSS',
        'align' => 'right',
        'default' => true,
        'currency_format' => true,
    ),
    'FI_MANAGER_NAME' => array(
        'width' => '10%',
        'label' => 'LBL_FI_MANAGER',
        'id' => 'FI_MANAGER_ID',
        'link' => true,
        'module' => 'Users',
        'default' => true,
        'related_fields' => array('fi_manager_id'),
    ),
    'DATE_ENTERED' => array(
        'width' => '10%',
        'label' => 'LBL_DATE_ENTERED',
        'default' => true,
    ),
    'ASSIGNED_USER_NAME' => array(
        'width' => '10%',
        'label' => 'LBL_LIST_ASSIGNED_USER',
        'module' => 'Employees',
        'id' => 'ASSIGNED_USER_ID',
        'default' => false,
    ),
    'AMOUNT_FINANCED' => array(
        'width' => '10%',
        'label' => 'LBL_AMOUNT_FINANCED',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'TERM_MONTHS' => array(
        'width' => '8%',
        'label' => 'LBL_TERM_MONTHS',
        'align' => 'center',
        'default' => false,
    ),
    'SELL_RATE' => array(
        'width' => '8%',
        'label' => 'LBL_SELL_RATE',
        'align' => 'right',
        'default' => false,
    ),
    'LENDER_NAME' => array(
        'width' => '12%',
        'label' => 'LBL_LENDER_NAME',
        'id' => 'LENDER_ID',
        'link' => true,
        'module' => 'Accounts',
        'default' => false,
        'related_fields' => array('lender_id'),
    ),
    'BACKEND_GROSS' => array(
        'width' => '10%',
        'label' => 'LBL_BACKEND_GROSS',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'FRONTEND_GROSS' => array(
        'width' => '10%',
        'label' => 'LBL_FRONTEND_GROSS',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'FUNDING_DATE' => array(
        'width' => '10%',
        'label' => 'LBL_FUNDING_DATE',
        'default' => false,
    ),
    'CONTRACT_DATE' => array(
        'width' => '10%',
        'label' => 'LBL_CONTRACT_DATE',
        'default' => false,
    ),
    'SALESPERSON_NAME' => array(
        'width' => '10%',
        'label' => 'LBL_SALESPERSON',
        'id' => 'SALESPERSON_ID',
        'link' => true,
        'module' => 'Users',
        'default' => false,
        'related_fields' => array('salesperson_id'),
    ),
    'OPPORTUNITY_NAME' => array(
        'width' => '12%',
        'label' => 'LBL_OPPORTUNITY_NAME',
        'id' => 'OPPORTUNITY_ID',
        'link' => true,
        'module' => 'Opportunities',
        'default' => false,
        'related_fields' => array('opportunity_id'),
    ),
    'DOWN_PAYMENT' => array(
        'width' => '10%',
        'label' => 'LBL_DOWN_PAYMENT',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'TRADE_ALLOWANCE' => array(
        'width' => '10%',
        'label' => 'LBL_TRADE_ALLOWANCE',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'WARRANTY_TOTAL' => array(
        'width' => '10%',
        'label' => 'LBL_WARRANTY_TOTAL',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'GAP_AMOUNT' => array(
        'width' => '10%',
        'label' => 'LBL_GAP_AMOUNT',
        'align' => 'right',
        'default' => false,
        'currency_format' => true,
    ),
    'DATE_MODIFIED' => array(
        'width' => '10%',
        'label' => 'LBL_DATE_MODIFIED',
        'default' => false,
    ),
); 